### ISSUE TITLE
Missing dependencies for version 0.9.0

### ISSUE THREAD

**Issue by nfleury** [RedisLabs/JRediSearch#10]
When including following dependency:

    <dependency>
      <groupId>com.redislabs</groupId>
      <artifactId>jredisearch</artifactId>
      <version>0.9.0</version>
    </dependency>

A dependency is missing: com.redislabs:jredisearch-jedis-3.0.0-sources.jar:jar:0.9.0 

It cannot be found from central repository or sonatype

**Comment by mnunberg** [comment]
This should be fixed in version 0.10.0 which i've just released.

**Comment by mnunberg** [comment]
It might take a while for maven central to update though.

**Comment by nfleury** [comment]
@mnunberg Thanks !

**Comment by KimDroid** [comment]
Thanks!
