### ISSUE TITLE
NoSuchMethodError when create index

### ISSUE THREAD

**Issue by mrvanhieu** [RedisLabs/JRediSearch#11]
I got below exception when trying to run the sample code in readme: 

```
Client client = new Client("eis", "localhost", 6379);
		Schema sc = new Schema()
				.addTextField("title", 5.0)
				.addTextField("body", 1.0)
				.addNumericField("price");

		client.createIndex(sc, Client.IndexOptions.Default());
```

```
java.lang.NoSuchMethodError: redis.clients.jedis.BinaryClient.sendCommand(Lredis/clients/jedis/commands/ProtocolCommand;[Ljava/lang/String;)V
	at io.redisearch.client.Client.sendCommand(Client.java:147) ~[jredisearch-0.10.0.jar:na]
	at io.redisearch.client.Client.createIndex(Client.java:176) ~[jredisearch-0.10.0.jar:na]
```
My pom.xml:
```
		<dependency>
			<groupId>com.redislabs</groupId>
			<artifactId>jredisearch</artifactId>
			<version>0.10.0</version>
		</dependency>
```
My dockerfile as below:
```
FROM redislabs/redisearch
#COPY ./_docker/conf/redis.conf /etc/redis/redis.conf
#ENTRYPOINT ["redis-server", "/etc/redis/redis.conf", "--loadmodule", "/usr/lib/redis/modules/redisearch.so"]
CMD ["redis-server", "--loadmodule", "/usr/lib/redis/modules/redisearch.so"]
```

The module version is:
```
127.0.0.1:6379> module list
1) 1) "name"
   2) "ft"
   3) "ver"
   4) (integer) 10100
```

Thanks,

**Comment by mnunberg** [comment]
It sounds like a dependency issue in runtime. Let me investigate

**Comment by mnunberg** [comment]
It should work. Are you sure you're not using a snapshot repository by accident?

**Comment by mrvanhieu** [comment]
It looks like the dependency is messed up when I was trying to hook JRediSearch with my existing project. I created a new project and didn't see the issue anymore

**Comment by mrvanhieu** [comment]
@mnunberg , is there anyway to create a new Client which connect to Redis host with password? I checked in io.redisearch.client.Client class and don't see anywhere to pass the password.

Thanks,

**Comment by mnunberg** [comment]
The dependency issues will be resolved. I can wrap the constructor to allow a password.

**Comment by mnunberg** [comment]
https://github.com/RedisLabs/JRediSearch/commit/353625955250eea0f19b0a594d246bdab901b0e1
