### ISSUE TITLE
Can aggregation function  be used for java ??

### ISSUE THREAD

**Issue by gm06041** [RedisLabs/JRediSearch#12]
I tried something about aggregation function with JAVA
but it didn't work well.
is it on going??

**Comment by mnunberg** [comment]
Can you post an example and output of what you've tried?

**Comment by gm06041** [comment]
when i tried by console, it was done well below.
<pre>
[gm0604@localhost src]$ ./redis-cli 
127.0.0.1:6379> FT.CREATE test_index SCHEMA name TEXT SORTABLE count NUMERIC SORTABLE
OK
127.0.0.1:6379> FT.ADD test_index data1 1.0 FIELDS name abc count 10
OK
127.0.0.1:6379> FT.ADD test_index data2 1.0 FIELDS name def count 5
OK
127.0.0.1:6379> FT.ADD test_index data3 1.0 FIELDS name def count 25
OK
127.0.0.1:6379> FT.AGGREGATE test_index "*" GROUPBY 1 @name REDUCE SUM 1 @count AS sum SORTBY 2 @sum DESC
1) (integer) 2
2) 1) "name"
   2) "def"
   3) "sum"
   4) "30"
3) 1) "name"
   2) "abc"
   3) "sum"
   4) "10"
127.0.0.1:6379> 
</pre>

but, i tried with jrediseach 
<pre>
public class App 
{
    public static void main( String[] args )
    {
        Client client = new Client("test_index", "localhost", 6379);        

//        FT.AGGREGATE test_index "*" GROUPBY 1 @name REDUCE SUM 1 @count AS sum SORTBY 2 @sum DESC
        AggregationRequest r = new AggregationRequest()
        		.groupBy("@name",
        				Reducers.sum("@count").as("sum"))
        		.sortBy(SortedField.desc("@sum")).limit(10);
        		
        
     // actual search
        AggregationResult res = client.aggregate(r);
    }
}
</pre>
but, error was returned. 

<pre>
Exception in thread "main" java.lang.ClassCastException: java.lang.Long cannot be cast to java.util.List
	at io.redisearch.AggregationResult.<init>(AggregationResult.java:15)
	at io.redisearch.client.Client.aggregate(Client.java:208)
	at JRedisTest.JRedisTest.App.main(App.java:46)
</pre>

I tried to debug about error.
In AggregationResult, resp object was like that.
<pre>
resp	ArrayList<E>  (id=23)	
	[0]	Long  (id=36)	
	[1]	(id=40)	
	[2]	ArrayList<E>  (id=41)	
	[3]	(id=42)	
	[4]	ArrayList<E>  (id=45)	
	[5]	(id=46)	
	[6]	ArrayList<E>  (id=47)	
</pre>

**Comment by gm06041** [comment]
I tested with JRediSearch master branch (rev. c68b4717e7185d71d864c5b1a5dd198360a6db08)
and RediSearch master branch (rev. a2bf58360c84cc3fff40941ff65daebd98ab2aba)

**Comment by gm06041** [comment]
did you check about this issue?

**Comment by mnunberg** [comment]
Hi, https://github.com/RedisLabs/JRediSearch/commit/cf8323683fe3d74aa07003d1a617528cda9f4a12 should fix it. The aggregation API in java may still change though, but should be good enough. Let me know if you have any more issues with this.
