### ISSUE TITLE
Redis search client library is incompatible with redis cache

### ISSUE THREAD

**Issue by Niksharma** [RedisLabs/JRediSearch#16]
I am trying to add redis cache as well as redis search in my application but, the client libraries keep clashing and can either be enabled for redisearch or redis cache. Is there a possible solution that can be applied to have them both?

**Comment by mnunberg** [comment]
Can you show me what is clashing?

**Comment by gkorland** [comment]
@Niksharma Can you please extend? what error are you getting?

**Comment by Niksharma** [comment]
Hi Guy,

I apologize for not responding earlier. The issue comes when spring data
redis is used along with Jedis libraries for redis cache. Now, after adding
rediSearch libraries for search capabilities the cache libraries won’t work
as the sendCommand method signature in the  rediSearch libraries is
incompatible with the one in Jedis library.

Please let me know if you still need more details.

Thanks,
Nikhil Sharma

**Comment by gkorland** [comment]
Can you try with the latest [Jedis](https://github.com/xetorthio/jedis)? (jedis-3.0.0-SHNAPSHOT)
JRediSearch works with this version.

**Comment by Niksharma** [comment]
Hi Guy,

Thanks for the update but, I have already switched the cache library to use
Lettuce.

Thanks,
Nikhil Sharma
