### ISSUE TITLE
Tag Support

### ISSUE THREAD

**Issue by jcolgan-r7** [RedisLabs/JRediSearch#19]
It seems that this library lacks support for tags.
I can't find a way to create a schema with tags. Searching by tags does work well, however it would also be nice to have this as part of the API rather than having to specify it in the query string.

**Comment by itamarhaber** [comment]
Hello @jcolgan-r7 

Thanks for raising this flag. It appears that this client is lagging behind the latest release - we'll try to update it asap.

**Comment by ethanhann** [comment]
@itamarhaber Is this in the works? Should I take a crack at it?

**Comment by ethanhann** [comment]
fyi, I took a crack at it.

**Comment by itamarhaber** [comment]
Thanks @ethanhann !
