### ISSUE TITLE
JedisSentinelPool support in RediSearch Client

### ISSUE THREAD

**Issue by chandu-atina** [RedisLabs/JRediSearch#22]
In the current implementation, as part of client initialization JedisPool is created in order to interact with Redis. My proposal is to provide support for JedisSentinelPool as well with redisearch client. User should be able to use either JedisPool or JedisSentinelPool based on their Redis Setup.

JedisSentinelPool will helps in automatic failover when master node changes from one node to another in typical Redis Master-Slave setup.

@mnunberg @itamarhaber 
I'm happy to contribute for the proposal if you guys are ok with the proposal.

**Comment by itamarhaber** [comment]
Hello @chandu-atina 

A PR would be amazing - thanks!

**Comment by chandu-atina** [comment]
https://github.com/RedisLabs/JRediSearch/pull/23

**Comment by chandu-atina** [comment]
PR implementing the above functionality has been merged into master. 
Closing the ticket
