### ISSUE TITLE
Search with special characters not giving correct result

### ISSUE THREAD

**Issue by katariakapil** [RedisLabs/JRediSearch#25]
Hi

When we are searching with special characters, its not giving correct result.  For example see below results.

127.0.0.1:6379> FT.SEARCH myIdx "hello>a*"
1) (integer) 0
127.0.0.1:6379> FT.SEARCH myIdx "hello>ab*"
1) (integer) 1
2) "doc2"
3) 1) "title"
   2) "hello>ab"
   3) "body"
   4) "lorem ipsum"
   5) "url"
   6) "http://redis.io"

When searching for hello>a* its not returning data, but when searching hello>ab* results are returned.  Could you please let us know why its not returning data.

**Comment by itamarhaber** [comment]
Hi @katariakapil 

This appears to be related to RediSearch (https://github.com/RedisLabs/RediSearch) rather than JRediSearch.

In any case, please refer to the documentation at https://oss.redislabs.com/redisearch/Configuring/#minprefix to understand prefix search's behavior.
