### ISSUE TITLE
Error when instantiating Client: java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by ethanhann** [RedisLabs/JRediSearch#39]
When I instantiate the Client class I get the error below. Any idea what the cause of this is?

**My setup...**
Ubuntu: 16.04
Java: 1.8.0_181
JRediSearch: master branch
Jedis: [3.0.0-20180508](https://mvnrepository.com/artifact/com.redislabs/jredisearch-jedis)
Pool Class: JedisPool
RediSearch: 1.4.0
Redis: 4.0.11

**Error output...**
```
2018-09-30 22:03:40,379 ERROR [io.undertow.request] (default task-43) UT005023: Exception handling request to /cqt/searchIndex.do: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    io/redisearch/client/Client.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/Set;IILjava/lang/String;)V @28: putfield
  Reason:
    Type 'redis/clients/jedis/JedisSentinelPool' (current frame, stack[1]) is not assignable to 'redis/clients/jedis/util/Pool'
  Current Frame:
    bci: @28
    flags: { }
    locals: { 'io/redisearch/client/Client', 'java/lang/String', 'java/lang/String', 'java/util/Set', integer, integer, 'java/lang/String', 'redis/clients/jedis/JedisPoolConfig' }
    stack: { 'io/redisearch/client/Client', 'redis/clients/jedis/JedisSentinelPool' }
  Bytecode:
    0x0000000: 2ab7 0002 2a15 05b7 0003 3a07 2abb 000c
    0x0000010: 592c 2d19 0715 0419 06b7 000d b500 062a
    0x0000020: 2bb5 0007 2abb 0008 59b7 0009 b500 0ab1
    0x0000030:                                        

	at com.example.search.Index.<init>(Index.java:24)
```

**Comment by ethanhann** [comment]
Maybe I'm using the wrong Jedis client? There seems to be 3...
1. https://mvnrepository.com/artifact/com.redislabs/jredisearch-jedis
2. https://mvnrepository.com/artifact/com.redislabs/jedis
3. https://mvnrepository.com/artifact/redis.clients/jedis

I'm using the first one (jredisearch-jedis). Is that the correct library? #33 mentions a newer version of jredisearch-jedis than what is in the artifact repo. Do I need to upgrade to that version?

**Comment by ethanhann** [comment]
This problem went away after I rebuilt my project from scratch. I think I must have done something to somehow mess up Jedis. idk. I'm going to go ahead and close this.

**Comment by bewidsandy** [comment]
@ethanhann I'm facing the same issue, In my spring boot 2.2 project, I have added dependency for both artifactories : jedis 2.9.0 and jredisearch 0.20.0. Could you please help how did you resolve the issue?

**Comment by gkorland** [comment]
@bewidsandy notice jredisearch 0.20.0 requires jedis 3.0.1 and above
