### ISSUE TITLE
RangeValue does not support long numeric. When does it support?

### ISSUE THREAD

**Issue by jameycai** [RedisLabs/JRediSearch#48]
RangeValue does not support long. What does it support?

eg:  1. query 19 bit long numeric , Values.eg(-7989522793807773965)
       2. query 13 bit milliseconds, Values.between(1531152000000, 1543507200000)

**Comment by gkorland** [comment]
duplicate #47

**Comment by gkorland** [comment]
RediSearch currently supports up to 48bit values

**Comment by jameycai** [comment]
Values.eg only supports int type , don't supports long  numeric type?
