### ISSUE TITLE
Query special strings is not supported, returns empty data. 

### ISSUE THREAD

**Issue by jameycai** [RedisLabs/JRediSearch#49]
Query special strings is not supported,   returns empty data.  eg:  Special string:  midline(-),  colon(:) 
 
   eg:  Node n = intersect().add("searchcode", "sgctransfer117-192.168.95.117:prt:124");

**Comment by gkorland** [comment]
RediSearch is using these tags to tokenize the String 
See how you can workaround it:
https://oss.redislabs.com/redisearch/Tags/#multi-word_tags_and_escaping
https://oss.redislabs.com/redisearch/Escaping/

**Comment by jameycai** [comment]
Thank you!
