### ISSUE TITLE
jedis connection should be closed in finally block.

### ISSUE THREAD

**Issue by eyes2near** [RedisLabs/JRediSearch#5]
currently, connection is closed after a redis command is executed, this may cause a connection leak when that command is failed to execute and throws an exception. codes should be put into a try-finally block.

**Comment by dvirsky** [comment]
@eyes2near right, care to make a PR?

**Comment by dragnot** [comment]
the Jedis.close() doesn't close the connection it returned it to the pool.
this is the correct way to work with Jedis connection pool.

**Comment by mnunberg** [comment]
Fixed in master
