### ISSUE TITLE
Missing check on existence of index before performing a 'dropIndex' 

### ISSUE THREAD

**Issue by skulkarnibvb** [RedisLabs/JRediSearch#8]
Any api - to check if the index exists, before dropping the same?
OR
An atomic operation - dropIfExists?

**Comment by mnunberg** [comment]
I'll add a `missingOk` boolean parameter.

**Comment by skulkarnibvb** [comment]
Thank you - I will wait for the release.

**Comment by mnunberg** [comment]
fixed in master.
